---
functional:
  -
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
implicit:
  - Батлы должны работать на JavaScript, PHP, Python и Ruby
  - Имеется возможность отслеживать через расширение в браузере
